# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 05:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 5, 25, 1, 648566, tzinfo=utc)),
        ),
    ]
